# Generated by Django 5.2.4 on 2025-07-12 10:54

import django.db.models.deletion
import qa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.CreateModel(
            name='AnswerContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order in which this block appears in the answer.')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=5)),
                ('text', models.TextField(blank=True, help_text='Text content, if this is a text block.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image content, if this is an image block.', null=True, upload_to=qa.models.answer_image_upload_path)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='qa.answer')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('answer', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='AnswerImage',
        ),
    ]
